name: .NET Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-dotnet.yml
    with:
      db_string: ${{ secrets.DB_STRING }}
    secrets:
      DB_STRING: ${{ secrets.DB_STRING }}
