name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: towfinder
          MYSQL_USER: towuser
          MYSQL_PASSWORD: towpassword

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Update this to your required .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Apply EF Core migrations
      env:
        ASPNETCORE_ENVIRONMENT: Development
        ConnectionStrings__DefaultConnection: Host=213.238.183.134;Database=furkanba3_towfinder;Username=furkanba3_fbrn21;Password=Fener2134*
      run: dotnet ef database update

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v2
      with:
        name: published_app
        path: ./publish
